server:
  port: 8888


mybatis:
  type-aliases-package: com.zhanghui.poem.entity
  mapper-locations: classpath:mapper/*.xml

#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC           #url
    username: root
    password: 302767241
  #配置es连接
  data:
    elasticsearch:
      cluster-nodes:  192.168.32.157:9300

      #redis配置集群节点
      #redis:
      #cluster:
      #nodes: 192.168.32.140:7000,192.168.32.140:7001,192.168.32.140:7002,192.168.32.140:7003,192.168.32.140:7004,192.168.32.140:7005
    #
    #redis:
    # host: 192.168.32.157
    # port: 6379

#运行日志配置
logging:
  level:
    root: info                                    #根日志的级别
    com.zhanghui.dao: debug                       #子日志